---
name: Squeezelite
version: 2.0.12
slug: squeezelite
description: Squeezelite client standalone on home assistant
url: https://github.com/cociweb/squeezelite-addon
startup: services
arch:
  - aarch64
  - armhf
  - amd64
  - i386
init: false
map: 
  - config
boot: auto
hassio_api: true
hassio_role: default
#host_network: true
privileged: list(DAC_READ_SEARCH|IPC_LOCK|NET_ADMIN|SYS_ADMIN)
full_access: true
audio: true
options:
  log_level: info
  name: Home Assistant Squeezelite
  output: default
  clientmac: 0A:0B:0C:0D:0E:0F
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  server: str?
  output: str
  clientmac: str
homeassistant: 2024.5.0
image: ghcr.io/cociweb/{arch}-addon-squeezelite
